### ISSUE TITLE
failed to run driver   pfn: failed to set alignment

### ISSUE THREAD

**Issue by graceleeis** [intel/pmem-csi#964] opened 2021-05-26 07:24 UTC
Hi

On master node, I run` kubectl create -f deploy/kubernetes-1.19/pmem-csi-lvm.yaml`, and got 
```
pmem-csi      pmem-csi-intel-com-controller-0      1/1     Running            0          12s
pmem-csi      pmem-csi-intel-com-node-48c4b        2/3     CrashLoopBackOff   1          12s

```
I run `kubectl -n pmem-csi logs  pmem-csi-intel-com-node-48c4b`, and got
`error: a container name must be specified for pod pmem-csi-intel-com-node-48c4b, choose one of: [pmem-driver driver-registrar external-provisioner]`

so I run` kubectl -n pmem-csi logs  pmem-csi-intel-com-node-48c4b -c pmem-driver`, and got
```
I0526 07:11:24.074129       1 main.go:69] Version: v0.9.0-88-g602e0f88
I0526 07:11:24.074799       1 pmd-lvm.go:326] Create fsdax-namespaces in region1, allowed 100 %, real align 6442450944:
total       :    1623497637888
avail       :    1623497637888
can use     :    1623497637888
I0526 07:11:24.075264       1 pmd-lvm.go:358] Create 1623497637888-bytes fsdax-namespace
failed to run driver: failed to create PMEM namespace with size '1623497637888' in region 'region1': pfn: failed to set alignment: Invalid argument
```
Can you please tell me what's wrong? Thanks!

**Comment by pohly** [comment] 2021-05-26 08:12
What does `ndctl list -NR` report on the affected node?

**Comment by graceleeis** [comment] 2021-05-26 08:16
Thank you for your reply!
if run `ndctl list -NR` on affected node, it shows
```
[
  {
    "dev":"region1",
    "size":1623497637888,
    "align":100663296,
    "available_size":1623497637888,
    "max_available_extent":1623497637888,
    "type":"pmem",
    "iset_id":3584442301718277324,
    "persistence_domain":"memory_controller"
  },
  {
    "dev":"region0",
    "size":1623497637888,
    "align":100663296,
    "available_size":1623497637888,
    "max_available_extent":1623497637888,
    "type":"pmem",
    "iset_id":6858559233618422988,
    "persistence_domain":"memory_controller"
  }
]

```

if run `ndctl list -N`, output nothing.
if run `ls /dev/pmem*`, it shows
`ls: cannot access '/dev/pmem*': No such file or directory`

**Comment by pohly** [comment] 2021-05-26 10:06
@okartau any ideas?

**Comment by okartau** [comment] 2021-05-26 13:13
Lack of /dev/pmem* is not problem at that point, a device is supposed to appear after namespace gets created (which does not succeed yet)
I hope you also can run ipmctl on the host (if not there, it should be installable), can you please run:
ipmctl show -memoryresources
ipmctl show -dimm
ipmctl show -region

The alignment value in region is reported 96MB, where I usually have seen 16MB there. This seems to be 6-way interleaved setup, based on log msg where pmem-csi thinks alignment is 6 GB (6 x 1GB). 
Can you share some details, what is this host, CPU, and what generation and type is PMEM memory?

**Comment by graceleeis** [comment] 2021-05-26 13:50
yes, you're right, we have 6 PMEM on each socket. CPU is: Genuine Intel(R) CPU 0000%@, which is not product CPU, it is a neoncity. PMEM is Apache pass 256G/each, os is Fedora 32 (Server Edition), kernel is 5.11.19-100.fc32.x86_64.
`sudo ipmctl show -memoryresources`
 ```
MemoryType   | DDR         | PMemModule   | Total
==========================================================
 Volatile     | 191.000 GiB | 0.000 GiB    | 191.000 GiB
 AppDirect    | -           | 3024.000 GiB | 3024.000 GiB
 Cache        | 0.000 GiB   | -            | 0.000 GiB
 Inaccessible | 1.000 GiB   | 5.452 GiB    | 6.452 GiB
 Physical     | 192.000 GiB | 3029.452 GiB | 3221.452 GiB
```
 `sudo ipmctl show -dimm`
 ```
DimmID | Capacity    | LockState | HealthState | FWVersion
===============================================================
 0x0001 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x0011 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x0021 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x0101 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x0111 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x0121 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x1001 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x1011 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x1021 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x1101 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x1111 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
 0x1121 | 252.454 GiB | Disabled  | Healthy     | 01.02.00.5446
```
`sudo ipmctl show -region`
 ```
SocketID | ISetID             | PersistentMemoryType | Capacity     | FreeCapacity | HealthState
==================================================================================================
 0x0000   | 0x5f2e7f48e6cd2ccc | AppDirect            | 1512.000 GiB | 1512.000 GiB | Healthy
 0x0001   | 0x31be7f483fcd2ccc | AppDirect            | 1512.000 GiB | 1512.000 GiB | Healthy
```

**Comment by okartau** [comment] 2021-05-26 17:33
Can we also get this please:
ipmctl show -system  -capabilities

I have no good ideas what is going wrong. In early times with pmem-csi, we sometimes saw such errors, and mostly these were related to alignment values. The 96MB value is exotic, I wonder where that comes from. I don't think one can set alignment value in ipmctl when creation regions. Do you happen to know how the regions were initially created?

**Comment by graceleeis** [comment] 2021-05-27 01:52
regions was created by me through `ipmctl create -goal PersistentMemoryType=AppDirect`
I checked with other colleagues, their alignment is also 1G. How to change this value? I searched[ ipmctl user guide](https://docs.pmem.io/ipmctl-user-guide/module-discovery/show-system-capabilities), but it didn't show how to change.
`sudo ipmctl show -system -capabilities`
```
PlatformConfigSupported=1
Alignment=1.000 GiB
AllowedVolatileMode=Memory Mode
CurrentVolatileMode=1LM
AllowedAppDirectMode=App Direct
```

**Comment by pohly** [comment] 2021-05-31 06:13
> How to change this value?

This sound like a question for the Optane hardware folks. In PMEM-CSI we usually don't deal with such low-level hardware details. But it is not clear whether it can be changed, so:

@okartau: given that the 96MB alignment is reported by ndctl for the region, shouldn't PMEM-CSI consider that when setting up the namespace?

**Comment by okartau** [comment] 2021-05-31 06:34
Reported alignment 1G by `ipmctl show -system -capabilities` is not a sign of problem, I think. On an older system (wolfpass) I see exactly same values reported.
But as I said, 96MB reported in region attributes differs from what I see on older system (16 MB, even when using interleaved setup). But then again, that may also be just normal and system specific, as I see 96 MB shown in [documented example](https://docs.pmem.io/ndctl-user-guide/managing-namespaces)

**Comment by okartau** [comment] 2021-05-31 06:38
> given that the 96MB alignment is reported by ndctl for the region, shouldn't PMEM-CSI consider that when setting up the namespace?

In days when we wrote pmem-csi code, the possible set for alignment values was fixed, I recall we had choices 4k, 2M, 128M  (?) 1G or something like that, from which only 1G appeared to working in all configurations we tested on. Now in doc, I don't see strict list documented any more in ndctl docs, does that mean one can use more values?

**Comment by okartau** [comment] 2021-05-31 06:41
One idea to try: please check can you create namespaces using ndctl on a node. Such trials are quicker than running pmem-csi, and you can try different sizes and alignment values. pmem-csi always uses alignment=1G and we cant change that easily without rebuilding. Trial without pmem-csi could help to point out is the problem in platform config, or in pmem-csi.

**Comment by okartau** [comment] 2021-05-31 18:59
> given that the 96MB alignment is reported by ndctl for the region, shouldn't PMEM-CSI consider that when setting up the namespace?

With ndctl CLI I can't use value of 96M for alignment:
`Error: align must be a power-of-2 greater than 4096`

**Comment by okartau** [comment] 2021-05-31 19:07
> One idea to try: please check can you create namespaces using ndctl on a node

Example command (verified with ndctl v71.1 here):
To create a 16G namespace with 1G alignment, which is close to what pmem-csi would create via libndctl:

`ndctl create-namespace -r region1 -a 1G -s 16G -n pmem-csi`

(you may need to substitute your region name)
"pmem-csi" is name that pmem-csi uses when creating namespaces. In LVM mode, this serves for own vs foreign recognition.
If you have trouble getting namespaces created by pmem-csi, but you can create namespaces on a node using ndctl, then
it is possible to reach working state in mixed fashion:
a) create namespaces by hand uisng ndctl, using name "pmem-csi"
b) start pmem-csi which recognizes such namespace(s) and will use them for volume provisioning

Such method is meant for debug and trial purposes, of course.

**Comment by pohly** [comment] 2021-06-03 16:16
> ndctl create-namespace -r region1 -a 1G -s 16G -n pmem-csi

@graceleeis you tried that and it didn't work, right? What was the error that you got?

**Comment by sscargal** [comment] 2021-06-04 19:36
I looked at a few different PMem hosts (different Linux distros, kernel versions, and OEMs) and they're all showing 96MiB alignment for the Region, which is okay. From the `ndctl-create-namespace(1)` man page:

```
Note both fsdax and devdax mode require 16MiB physical alignment to be cross-arch compatible.
```

16MiB * 6 PMem Modules in the Region == 96MiB.

Q) What is/was reported to dmesg or /var/log/messages around the time of the error? We should find some Kernel or driver messages.

I like where Patrick is going here. If manually creating the namespace using `ndctl` works, then we know to look in the pmem-csi code. If ndctl also fails, then we need to look in the Kernel/Host side. 

I don't see any obvious issues in setupNS() where the error originates: https://github.com/intel/pmem-csi/blob/3bb02461474881963c52069ac7cebdd9560490b1/pkg/pmem-device-manager/pmd-lvm.go#L317

Experiments using ndctl on Fedora 33 with Kernel 5.10.10 and 5.12.8 using the input values from pmem-csi works. I have the same 2-2-2 config using 256GB PMem modules on a Wolfpass (S2600WF). Neon City has a different BIOS and HW layout, which may or may not be a factor. 

```
# ndctl list -RN
[
  {
    "dev":"region1",
    "size":1623497637888,
    "align":100663296,
    "available_size":1623497637888,
    "max_available_extent":1623497637888,
    "type":"pmem",
    "iset_id":-2506113243053544244,
    "persistence_domain":"memory_controller"
  },
  {
    "dev":"region0",
    "size":1623497637888,
    "align":100663296,
    "available_size":1623497637888,
    "max_available_extent":1623497637888,
    "type":"pmem",
    "iset_id":3259620181632232652,
    "persistence_domain":"memory_controller"
  }
]

// Testing with 1GiB alignment
# ndctl create-namespace --region 0 --size 1623497637888 --align 1G
{
  "dev":"namespace0.0",
  "mode":"fsdax",
  "map":"dev",
  "size":"1487.00 GiB (1596.65 GB)",
  "uuid":"033600f7-85a5-47f8-b421-4b3a9d4499a0",
  "sector_size":512,
  "align":1073741824,
  "blockdev":"pmem0"
}

// Testing with 2MIB alignment (default)
# ndctl create-namespace --region 1 --size 1623497637888 
{
  "dev":"namespace1.0",
  "mode":"fsdax",
  "map":"dev",
  "size":"1488.37 GiB (1598.13 GB)",
  "uuid":"64740374-7ba2-4c1c-8cf6-c2f6159ffef4",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem1"
}
```

**Comment by pohly** [comment] 2021-06-07 07:56
From a private email we know that `ndctl create-namespace` worked and created a namespace with an alignment of 2MiB.

That PMEM-CSI hard-codes 1GiB as alignment seems to be historic. We need to reconsider that.

@sscargal do you know what the current guidance on that is? Are there any known cases where the default alignment of 2MiB is not working and/or undesirable?

**Comment by sscargal** [comment] 2021-06-07 14:46
@pohly 2MiB has been the default for FSDAX from the beginning, with no known issue reported. 1GiB pages could be useful on very large memory systems to avoid or reduce TLB misses.

**Comment by okartau** [comment] 2021-06-07 16:14
We faced trouble creating namespaces with 2MB alignment with some older kernels, and we did not want to introduce kernel dep because of that. 1GB alignment worked on all platforms we tested on, so this was hard-coded. This was all back in 2018, things may have changed. 
Sure, such hard-coding is not nice and seems it may be related to this issue. Should we try to get rid of hard-coded alignment and leave it to libndctl to decide (i.e. will use 2MB). We may need to re-check some other assumptions about sizes as well.

**Comment by okartau** [comment] 2021-06-07 17:24
I looked can we stop specifying alignment and leave it to libndctl to pick default, but seems this is not easy: size has to be aligned by "real alignment" which is alignment * interleave_ways, and to calculate that, I have to know alignment that will be used, already before making creation request. Is there API to query which alignment libndctl would use? I wonder how that works (not giving alignment as argument) in command line case, does the size get adjusted (down) there dynamically? 
In pmem-csi we cant allow size getting smaller than our request is, thats why we have such complex allocation scheme that looks into alignment, size, and interleave_ways already before making creation request.

**Comment by pohly** [comment] 2021-06-07 17:39
> 1GB alignment worked on all platforms we tested on, so this was hard-coded. This was all back in 2018, things may have changed.

They probably have. Let's switch away from 1GiB alignment as default.

> Should we try to get rid of hard-coded alignment and leave it to libndctl to decide (i.e. will use 2MB).

Does it decide dynamically based on the region and/or kernel, or does it always use 2MiB by default unless told otherwise?

> In pmem-csi we cant allow size getting smaller than our request is, thats why we have such complex allocation scheme that looks into alignment, size, and interleave_ways already before making creation request.

That's https://github.com/intel/pmem-csi/issues/933 then.

We already established there that we cannot predict reliably how much larger we have to make the request. Let's change it so that we make a best-effort guess and if that guess turns out to be wrong (= resulting namespace too small), delete that namespace and try again with a larger request until it succeeds.

**Comment by graceleeis** [comment] 2021-06-08 05:46
> > ndctl create-namespace -r region1 -a 1G -s 16G -n pmem-csi
> 
> @graceleeis you tried that and it didn't work, right? What was the error that you got?

yes, it didn't work and show
```
$ ndctl create-namespace -r region1 -a 1G -s 16G -n pmem-csi
  Error: create namespace: region1: align setting is 0x6000000 size 0x400000000 is misaligned
```

**Comment by okartau** [comment] 2021-06-08 09:11
> $ ndctl create-namespace -r region1 -a 1G -s 16G -n pmem-csi
>   Error: create namespace: region1: align setting is 0x6000000 size 0x400000000 is misaligned

That indicates ndctl selects 96MB as actual alignment, despite 1G asked by option?
And then creation fails because 16G is indeed not aligned by 96MB.
How is that explainable by ndctl use POV?

**Comment by okartau** [comment] 2021-06-08 09:14
> They probably have. Let's switch away from 1GiB alignment as default.

I tried to select 2MB as alignment in an added commit in #938, but our CI systems (qemu based) then fail to create namespaces with "invalid argument". Perhaps this has something to do with fact that we do not specify align= argument in qemu options? I added align=2M there now to see does it help, job still running.

**Comment by pohly** [comment] 2021-06-08 14:05
> That indicates ndctl selects 96MB as actual alignment, despite 1G asked by option?

No, I think this is checking the requested size against the alignment of the region. The size parameter must be chosen so that it is a multiple of the region alignment.

**Comment by pohly** [comment] 2021-06-08 14:33
> Does it decide dynamically based on the region and/or kernel, or does it always use 2MiB by default unless told otherwise?

I looked for an answer to that and if I read the code right, it takes the alignment from the seed namespace:
https://github.com/pmem/ndctl/blob/ea014c0c9ec8d0ef945d072dcc52b306c7a686f9/ndctl/namespace.c#L804-L814

The fallback to 2MiB is only applicable to old kernels.

**Comment by pohly** [comment] 2021-06-08 14:55
In our QEMU machines, `ndctl create-namespace` uses a 2MiB alignment:
```
openat(AT_FDCWD, "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0012:00/ndbus0/region0/pfn0.0/align", O_WRONLY|O_CLOEXEC) = 3
write(3, "2097152\n\0", 9)              = 9
close(3)                                = 0
```

At least I think that's where it gets set... Yes, that's where "-a 1073741824" (the next bigger supported alignment) shows up.

> I tried to select 2MB as alignment in an added commit in #938, but our CI systems (qemu based) then fail to create namespaces with "invalid argument". 

I can't reproduce that with ndctl:
```
[fedora@pmem-csi-pmem-govm-master ~]$ sudo ndctl create-namespace -a 2M
{
  "dev":"namespace0.0",
  "mode":"fsdax",
  "map":"dev",
  "size":"63.00 GiB (67.64 GB)",
  "uuid":"abf9dffd-7f42-407a-a001-5b377780544b",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem0"
}
```

**Comment by okartau** [comment] 2021-06-08 14:55
> The size parameter must be chosen so that it is a multiple of the region alignment.

hm, this is new req? So far we have followed what is documented on ndctl man page:

For pmem namepsaces the size must be a multiple of the interleave-width and the namespace alignment

So now we have to choose value which satisfies both these rules? And this req. somehow surfaces with this new platform?
As on older platform creation of namespace works giving -a 1G.

**Comment by pohly** [comment] 2021-06-08 15:01
> hm, this is new req?

That was my understanding of the error message. I did not look up where it comes from. It's from here:
https://github.com/pmem/ndctl/blob/ea014c0c9ec8d0ef945d072dcc52b306c7a686f9/ndctl/namespace.c#L838-L843

Looks like that was added 16 months ago: https://github.com/pmem/ndctl/commit/ba9365cf46670c0fa089cb928fbf9d0dbead5e18

> As on older platform creation of namespace works giving -a 1G.

This particular error wasn't related to the chosen alignment, only about the namespace size.

**Comment by pohly** [comment] 2021-06-08 15:02
According to that commit message, the region alignment requirement already existed earlier, it just was checked by the kernel instead of ndctl. For PMEM-CSI that means that certain volume sizes fail with "invalid argument".

**Comment by pohly** [comment] 2021-06-08 15:03
> I tried to select 2MB as alignment in an added commit in #938, but our CI systems (qemu based) then fail to create namespaces with "invalid argument". 

Invalid argument for which operation?

**Comment by okartau** [comment] 2021-06-08 16:49
> Invalid argument for which operation?
It is namespace creation in direct mode.

It happened in this run:
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-938/7/

detailed log can be seen in job log. Your working example did not set size. We set size based on request, and in testing cases size can be relatively small. In one case what I looked, our testing code asks 110MB volume, size is increased because of our compensation and alignment checks, and the request will be 114 MB, and the trace is:
```
controllerserver-node.go:221 CreateVolume: Name:"pvc-84236392-ccc8-4746-af67-04afe231a9a5" req.Required:115343360 req.Limit:0
controllerserver-node.go:519 CreateVolume: Create VolumeID:pvc-84-95bcf28c30817baa69f91446f3a9a729dfc638e7c9e4f66801efcf92 based on name:pvc-84236392-ccc8-4746-af67-04afe231a9a5
pmd-ndctl.go:178 Compensate for libndctl creation overhead: increased request size to 119332864
region.go:206 region0: namespace size must align to interleave-width:1 * alignment:2097152, force-align to 119537664
ndctl.go:87 Namespace creation failure in region0: Failed to set namespace size: Invalid argument
```

I think what happens here is that use of 2 MB alignment makes us ask for small namespace, and it has been noted that allocations under 1G overall fail, but with alignment=1G we never made any small allocation request.
Does your ndctl working example still work when you ask for 114 MB size?

**Comment by pohly** [comment] 2021-06-08 18:53
> ndctl.go:87 Namespace creation failure in region0: Failed to set namespace size: Invalid argument

That's the operation that I meant. So as I guessed, the size is the problem.

> Does your ndctl working example still work when you ask for 114 MB size?

No:
```
[fedora@pmem-csi-pmem-govm-master ~]$ sudo ndctl create-namespace -a 2M -s 114M
  Error: create namespace: region0: align setting is 0x1000000 size 0x7200000 is misaligned
```

Rounding up to the next multiple of the region alignment should fix the problem. But we'll have to think about this holistically and also address the other known issues.

**Comment by KiChoudhary** [comment] 2021-06-15 07:08
I have run the driver for the interleaved configuration of the pmem devices. I get the following error:

```
[root@visetup common]# oc logs pod/pmem-csi-intel-com-node-hkbr7 -n pmem-csi -c pmem-driver
I0614 12:33:36.046585       1 main.go:69] Version: v0.9.0-151-g86340a5b
I0614 12:33:36.047345       1 pmd-lvm.go:326] Create fsdax-namespaces in region1, allowed 100 %, real align 4294967296:
total       :     893353197568
avail       :     893353197568
can use     :     893353197568
I0614 12:33:36.047850       1 pmd-lvm.go:358] Create 893353197568-bytes fsdax-namespace
failed to run driver: failed to create PMEM namespace with size '893353197568' in region 'region1': pfn: failed to set alignment: Invalid argument
```

But if I configure my pmem devices in not interleaved mode, all the namespaces are created. 

The command used:

```
ipmctl create -goal PersistentMemoryType=AppDirect

ipmctl create -goal PersistentMemoryType=AppDirectNotInterleaved
```

**Comment by okartau** [comment] 2021-06-17 08:09
I believe in a non-interleaved case the region alignment gets down to 16MB which works better.
Anyways, we yesterday merged an improvement PR #938 into branch=devel which addressed multiple size and alignment aspects, so a trial with code built from devel branch now could/should show better results

**Comment by pohly** [comment] 2021-06-21 06:05
@graceleeis: the current "canary" image should contain the fix for this. Can you perhaps verify that?

You should be able to update to that version by setting the `image` field in your deployment spec to `intel/pmem-csi-driver:canary`. Switching between different versions is not guaranteed to work, but I think in this case it is okay.

**Comment by graceleeis** [comment] 2021-08-23 08:40
verfied! it can work now, thanks!

**Closed** 2021-08-23 08:40 UTC
Labels: 1.0

**Comment by pohly** [comment] 2021-08-23 08:54
@graceleeis: Thanks for the confirmation. :+1:
