### ISSUE TITLE
Testing Kubernetes 1.20

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#886] opened 2021-02-08 08:25 UTC
We had to revert testing on 1.20 due to slower performance. We should bring it back as a branch in our main repo to cover full testing before merging.

**Comment by avalluri** [comment] 2021-03-03 20:57
The root cause for this slowness is the delay in terminating the Pods caused by [wait for sandbox deletion](https://github.com/kubernetes/kubernetes/issues/88543) introduced in Kubernetes 1.20. Kubelet waits for the container sandbox clean up even though the container got removed on pod deletion.

Kubelet log shows that the pod deletion started and the container got deleted:

```
kubelet[3772600]: I0220 19:58:42.721745 3772600 kubelet.go:1904] SyncLoop (DELETE, "api"): "pmem-csi-intel-com-controller-0_default(eb809dda-9a3d-4323-829d-7374c69158ff)"
....
kubelet[3772600]: I0220 19:58:42.727624 3772600 event.go:291] "Event occurred" object="default/pmem-csi-intel-com-controller-0" kind="Pod" apiVersion="v1" type="Normal" reason="Killing" message="Stopping container pmem-driver"
....
kubelet[3772600]: I0220 19:58:43.810817 3772600 manager.go:1044] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podeb809dda_9a3d_4323_829d_7374c69158ff.slice/cri-containerd-59e782be3f8244d740b3e74acf110239dbe81debf31c10ed58fddb2c7aa0b3d0.scope" (aliases: [59e782be3f8244d740b3e74acf110239dbe81debf31c10ed58fddb2c7aa0b3d0 /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podeb809dda_9a3d_4323_829d_7374c69158ff.slice/cri-containerd-59e782be3f8244d740b3e74acf110239dbe81debf31c10ed58fddb2c7aa0b3d0.scope], namespace: "containerd")/
```

but it still keeps the Pod as its sandboxes still not removed from the cache:

```
kubelet[3772600]: I0220 19:59:01.919363 3772600 kubelet_pods.go:975] Pod "pmem-csi-intel-com-controller-0_default(eb809dda-9a3d-4323-829d-7374c69158ff)" is terminated, but some pod sandboxes have not been cleaned up: {Id:0ab048ec6a8dfc6f037a937ea47b414dd6f430efcd923d30dac6713fcd7e5bef Metadata:&PodSandboxMetadata{Name:pmem-csi-intel-com-controller-0,Uid:eb809dda-9a3d-4323-829d-7374c69158ff,Namespace:default,Attempt:0,} State:SANDBOX_NOTREADY CreatedAt:1613832708831703748 Network:&PodSandboxNetworkStatus{Ip:192.168.133.150,AdditionalIps:[]*PodIP{},} Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:POD,Pid:CONTAINER,Ipc:POD,TargetId:,},},} Labels:map[app.kubernetes.io/component:controller app.kubernetes.io/instance:pmem-csi.intel.com app.kubernetes.io/name:pmem-csi-controller app.kubernetes.io/part-of:pmem-csi controller-revision-hash:pmem-csi-intel-com-controller-8b9ff7cfb io.kubernetes.pod.name:pmem-csi-intel-com-controller-0 io.kubernetes.pod.namespace:default io.kubernetes.pod.uid:eb809dda-9a3d-4323-829d-7374c69158ff pmem-csi.intel.com/deployment:direct-production pmem-csi.intel.com/webhook:ignore statefulset.kubernetes.io/pod-name:pmem-csi-intel-com-controller-0] Annotations:map[kubernetes.io/config.seen:2021-02-20T14:51:39.280155930Z kubernetes.io/config.source:api pmem-csi.intel.com/scrape:containers] RuntimeHandler: XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}
....
kubelet[3772600]: I0220 19:59:11.918596 3772600 kubelet_pods.go:975] Pod "pmem-csi-intel-com-controller-0_default(eb809dda-9a3d-4323-829d-7374c69158ff)" is terminated, but some pod sandboxes have not been cleaned up: {Id:0ab048ec6a8dfc6f037a937ea47b414dd6f430efcd923d30dac6713fcd7e5bef Metadata:&PodSandboxMetadata{Name:pmem-csi-intel-com-controller-0,Uid:eb809dda-9a3d-4323-829d-7374c69158ff,Namespace:default,Attempt:0,} State:SANDBOX_NOTREADY CreatedAt:1613832708831703748 Network:&PodSandboxNetworkStatus{Ip:192.168.133.150,AdditionalIps:[]*PodIP{},} Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:POD,Pid:CONTAINER,Ipc:POD,TargetId:,},},} Labels:map[app.kubernetes.io/component:controller app.kubernetes.io/instance:pmem-csi.intel.com app.kubernetes.io/name:pmem-csi-controller app.kubernetes.io/part-of:pmem-csi controller-revision-hash:pmem-csi-intel-com-controller-8b9ff7cfb io.kubernetes.pod.name:pmem-csi-intel-com-controller-0 io.kubernetes.pod.namespace:default io.kubernetes.pod.uid:eb809dda-9a3d-4323-829d-7374c69158ff pmem-csi.intel.com/deployment:direct-production pmem-csi.intel.com/webhook:ignore statefulset.kubernetes.io/pod-name:pmem-csi-intel-com-controller-0] Annotations:map[kubernetes.io/config.seen:2021-02-20T14:51:39.280155930Z kubernetes.io/config.source:api pmem-csi.intel.com/scrape:containers] RuntimeHandler: XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}
```

and finally removed from api/etcd server

```
Feb 20 19:59:31 pmem-csi-pmem-govm-worker1 kubelet[3772600]: I0220 19:59:31.961670 3772600 kubelet.go:1904] SyncLoop (DELETE, "api"): "pmem-csi-intel-com-controller-0_default(eb809dda-9a3d-4323-829d-7374c69158ff)"
Feb 20 19:59:31 pmem-csi-pmem-govm-worker1 kubelet[3772600]: I0220 19:59:31.962071 3772600 kubelet.go:1986] Pod "pmem-csi-intel-com-controller-0_default(eb809dda-9a3d-4323-829d-7374c69158ff)" has completed execution and should be deleted from the API server: update
Feb 20 19:59:31 pmem-csi-pmem-govm-worker1 kubelet[3772600]: I0220 19:59:31.962594 3772600 status_manager.go:443] Status Manager: adding pod: "eb809dda-9a3d-4323-829d-7374c69158ff", with status: (4, {Running [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2021-02-20 14:51:39 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2021-02-20 19:58:51 +0000 UTC ContainersNotReady containers with unready status: [pmem-driver]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2021-02-20 19:58:51 +0000 UTC ContainersNotReady containers with unready status: [pmem-driver]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2021-02-20 14:51:36 +0000 UTC  }]    172.17.0.4 192.168.133.150 [{192.168.133.150}] 2021-02-20 14:51:39 +0000 UTC [] [{pmem-driver {&ContainerStateWaiting{Reason:ContainerCreating,Message:,} nil nil} {nil nil &ContainerStateTerminated{ExitCode:137,Signal:0,Reason:ContainerStatusUnknown,Message:The container could not be located when the pod was deleted.  The container used to be Running,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} false 0 intel/pmem-csi-driver:canary   0xc001290ed8}] BestEffort []}) to podStatusChannel
Feb 20 19:59:32 pmem-csi-pmem-govm-worker1 kubelet[3772600]: I0220 19:59:32.163120 3772600 status_manager.go:591] Pod "pmem-csi-intel-com-controller-0_default(eb809dda-9a3d-4323-829d-7374c69158ff)" fully terminated and removed from etcd
```

Which takes around ~60s to delete the controller pod.

This [issue](https://github.com/kubernetes/kubernetes/issues/97288)  got reported in upstream and got addressed by [reverting the sandbox deletion code](https://github.com/kubernetes/kubernetes/pull/97980).

Moving to v1.20.4 supposed to improve the 1.20 testing.

**Comment by pohly** [comment] 2021-03-04 08:18
> Moving to v1.20.4 supposed to improve the 1.20 testing.

Can you try that?

**Comment by avalluri** [comment] 2021-03-04 08:41
> > Moving to v1.20.4 supposed to improve the 1.20 testing.
> 
> Can you try that?

Yes, I did that. But, CI failed with a bit strange errors:

```
[2021-03-03T21:24:10.365Z] + make test_e2e TEST_E2E_REPORT_DIR=/mnt/workspace/pmem-csi_k8s-120/build/reports.tmp/fedora-1_20 TEST_E2E_SKIP=
[2021-03-03T21:24:10.365Z] go: creating new go.mod: module tmp
[2021-03-03T21:24:10.365Z] go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.3.0
[2021-03-03T23:25:59.239Z] Mar  3 23:19:45.205: FAIL: container "driver-registrar" in pod "pmem-csi-intel-com-node-8czsp" restarted 1 times, last state: {Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2021-03-03 23:19:29 +0000 UTC,FinishedAt:2021-03-03 23:19:32 +0000 UTC,ContainerID:containerd://ea25498e1854cb5e05e1119be564f2f589f9c4540107eefbe439e825a370095f,}}
[2021-03-03T23:25:59.253Z] Mar  3 23:24:56.466: FAIL: clean up volumes
[2021-03-03T23:25:59.253Z] Mar  3 23:25:06.751: FAIL: same volumes before and after the test
[2021-03-03T23:25:59.253Z] Mar  3 23:25:08.518: FAIL: container "driver-registrar" in pod "pmem-csi-intel-com-node-8czsp" restarted 1 times, last state: {Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2021-03-03 23:19:29 +0000 UTC,FinishedAt:2021-03-03 23:19:32 +0000 UTC,ContainerID:containerd://ea25498e1854cb5e05e1119be564f2f589f9c4540107eefbe439e825a370095f,}}
[2021-03-03T23:25:59.253Z] Mar  3 23:25:13.098: FAIL: container "driver-registrar" in pod "pmem-csi-intel-com-node-8czsp" restarted 1 times, last state: {Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2021-03-03 23:19:29 +0000 UTC,FinishedAt:2021-03-03 23:19:32 +0000 UTC,ContainerID:containerd://ea25498e1854cb5e05e1119be564f2f589f9c4540107eefbe439e825a370095f,}}
```

**Comment by pohly** [comment] 2021-03-04 08:47
> [2021-03-03T23:25:59.239Z] Mar  3 23:19:45.205: FAIL: container "driver-registrar" in pod "pmem-csi-intel-com-node-8czsp" restarted 1 times, last state: {Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2021-03-03 23:19:29 +0000 UTC,FinishedAt:2021-03-03 23:19:32 +0000 UTC,ContainerID:containerd://ea25498e1854cb5e05e1119be564f2f589f9c4540107eefbe439e825a370095f,}}

We expect driver containers to keep running once started. In this case log messages for that container might explain why it restarted - that's what needs to be addressed.

**Comment by avalluri** [comment] 2021-03-05 08:16
> We expect driver containers to keep running once started. In this case log messages for that container might explain why it restarted - that's what needs to be addressed.

This was a false positive. The failure was in version-skew testing. The driver-registrar deployed in the v0.8 release runs with default(~1s) timeout which failed to connect to the driver.

```
pmem-csi-intel-com-node-8czsp/pmem-driver@pmem..ker1: I0303 23:19:32.037517       1 tracing.go:19] GRPC call: /csi.v1.Identity/GetPluginInfo
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:32.278837       1 connection.go:183] GRPC response: {}
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:32.449174       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: E0303 23:19:32.457424       1 main.go:133] error retreiving CSI driver name: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0303 23:19:32.682262    9821 exec.go:45] test/setup-deployment.sh: storageclass.storage.k8s.io/pmem-csi-sc-cache unchanged
pmem-csi-intel-com-node-8czsp/pmem-driver@pmem..ker1: I0303 23:19:32.042200       1 tracing.go:20] GRPC request: {}
pmem-csi-intel-com-node-8czsp/pmem-driver@pmem..ker1: I0303 23:19:32.674213       1 tracing.go:25] GRPC response: {"name":"pmem-csi.intel.com","vendor_version":"v0.8.0-238-gf790ae34"}
pmem-csi-intel-com-node-8czsp/external-provisioner@pmem..ker1: I0303 23:19:33.202556       1 connection.go:153] Connecting to unix:///csi/csi.sock
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: ==== end of pod log ====
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: ==== start of pod log ====
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:30.176667       1 main.go:110] Version: v1.2.0-0-g6ef000ae
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:30.176894       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:30.177193       1 connection.go:151] Connecting to unix:///csi/csi.sock
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:31.180708       1 main.go:127] Calling CSI driver to discover driver name
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:31.220474       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:31.224434       1 connection.go:181] GRPC request: {}
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:32.278837       1 connection.go:183] GRPC response: {}
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: I0303 23:19:32.449174       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
pmem-csi-intel-com-node-8czsp/driver-registrar@pmem..ker1: E0303 23:19:32.457424       1 main.go:133] error retreiving CSI driver name: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

[Rebuild](https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/k8s-120/4/pipeline/) shows all green. And the 1.20 build took ~7:35hrs

**Closed** 2021-03-05 18:17 UTC
