### ISSUE TITLE
cri-o: read-only /sys

### ISSUE THREAD

**Issue by pohly** [intel/pmem-CSI#112] opened 2018-12-21 08:35 UTC
When bringing up the simulator with TEST_CRI=crio in a `test/test-config.d/cri.sh` file, the `/sys` filesystem is read-only in the VM guests. That breaks initialization of the simulated PMEM. It works fine when using Docker.

The same is likely to happen when using cri-o on real hardware, therefore this issue needs to be investigated.

**Comment by okartau** [comment] 2019-02-13 09:19
/sys is read-only in pmem-csi pod in recent Clear-based test cluster even with TEST_CRI=docker.
Clear version is 27700.
I found this while running e2e test in devicemode:Direct, but it means failure should also happen
in devicemode:LVM, as initial stage of namespace creation should fail.

**Comment by okartau** [comment] 2019-02-13 10:41
in LVM mode, deployment and e2e test works in same cluster, means that in pmem-ns-init container /sys must be writable. What is the diff? One diff is that pmem-ns-init is classified as initContainer, but both containers are marked as privileged.

**Comment by okartau** [comment] 2019-02-13 11:37
We repeatedly seem to stumble to read-only /sys mount where we critically need read-write access.
The problem is exposed in some indirect way and giving potentially fuzzy error messages.
Situation may get changed by external-to-pmem-csi changes (k8s, docker, crio, clear) and
is therefore difficult to connect to known changes.
What about performing check for read-write mount of /sys during start of plugin, and refuse to continue (with clearly stated error msg) if there is no write access, as continuing would lead to errors anyway.
We need to run such check at start of:
- pmem-ns-init (initContainer) in devicemode:lvm
- pmem-driver in devicemode:ndctl

**Comment by okartau** [comment] 2019-02-13 11:54
Developing this idea one step further:
it would be very useful to detect isolated /dev in container, which leads to error path like in #168 in devicemode:direct. 
Detection of isolated /dev is not as easy as read-only /sys, I guess.
But if we can detect it, we don't need to develop not-so-clean solutions to #168, like #170 is,
as then we can avoid bad-state namespace creations altogether.

**Comment by okartau** [comment] 2019-02-14 07:34
With added explicit /sys mount in manifest, e2e test becomes runnable also with TEST_CRI=crio setting.
I made a test pass using devicemode:direct
However, run-time in crio mode  (2400 sec) is longer than typical (1600 sec) in docker mode, and there was one sanity-test  error. To be investigated more.

**Comment by okartau** [comment] 2019-03-14 13:42
We have now added:
- explicit mount of /sys for containers deployment (in direct mode) -- allows use of /sys by libndctl
- added start-time check-for-writable-sys inside pmem-csi driver -- helps to diagnose read-only state early with clear error message.
- added a chapter in DEVELOPMENT.md describing potential issues about /dev and /sys access in containers.

Is this enough to resolve this issue or can/should we do more?

**Comment by pohly** [comment] 2019-03-22 08:32
Sounds you have covered it. Not sure what else could be done, so unless you can think of something I'm fine with closing the issue.

**Comment by okartau** [comment] 2019-04-17 13:53
re-opening as there is scenario reported where LVM-mode pmem-ns-init can not write to /sys in initContainer. Not sure is is CRI-O involved.
Seems this issue got closed too early, there are uncovered cases.

**Comment by okartau** [comment] 2019-04-18 08:31
problem confirmed in local testing: cluster in TEST_CRI=cri mode created by `make start`:
Code of current devel branch, CID=f33437119e32fed04ef5336ed57e95f3b1238617
```
$ kubectl logs pmem-csi-v7bdh
I0418 08:21:55.651540       1 glog.go:79] Calculated canUse:34357641216, available by Region info:34357641216
I0418 08:21:55.651560       1 glog.go:79] Create next 10737418240-bytes fsdax-namespace
W0418 08:21:55.651742       1 glog.go:84] Failed to create namespace:Failed to set namespace uid: Read-only file system
```

next, let's try to add explicit mount of /sys in pmem-ns-init initContainer

**Comment by okartau** [comment] 2019-04-18 08:46
adding explicit /sys mount in pmem-ns-init avoids the read-only problem, I will create PR

**Comment by okartau** [comment] 2019-04-23 12:05
closing again as recently added explicit /sys mount made the known failing case working

**Closed by okartau** 2019-04-23 12:05 UTC
