### ISSUE TITLE
"capacity restored" test fails

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#322] opened 2019-07-01 18:44 UTC
After merging PR #196, the following test of the "devel" branch failed:
```
[Fail] sanity pmem csi [AfterEach] capacity is restored after controller restart 
/go/src/github.com/intel/pmem-csi/test/e2e/storage/sanity.go:109
```

https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-CSI/detail/devel/8/pipeline

**Comment by avalluri** [comment] 2019-07-02 12:12
#324 Is supposed to fix these type of test failures, caused by delay in the re-registering of Nodes on Controller restarts.

**Comment by pohly** [comment] 2019-07-02 13:09
Amarnath Valluri <notifications@github.com> writes:
> #324 Is supposed to fix these type of test failures, caused by delay
> in the re-registering of Nodes on Controller restarts.

That PR may shorten the delay, but the race condition remains.

**Comment by avalluri** [comment] 2019-07-09 09:33
#324 Has the needed fix and it's merged.

**Closed by avalluri** 2019-07-09 09:33 UTC
